export const produtosEstaticos = [
  {
    "id": 1,
    "nomeProduto": "Smartphone Samsung Galaxy A36 128GB 5G",
    "DescricaoCurta": "O Samsung Galaxy A36 5G Preto é um smartphone com tela imersiva Super Amoled com Vision Booster de 6,7\" e taxa de atualização de 120Hz. Ele vai te surpreender com tanta tecnologia envolvida em sua construção. Ele é equipado com processador Qualcomm Snapdragon 6 Gen 3 Octa-core, 128GB de armazenamento interno para ter diversos arquivos salvos e 6GB de memória RAM para não ter travamentos durante o uso.",
    "created_at": "2026-03-13 23:13:22.072154+00",
    "DescricaoLonga": "Para tirar inúmeras fotos, a câmera traseira é tripla de 50MP + 8MP + 5MP e a frontal, é de 12MP. A bateria é de 5000mAh com longa duração para assistir a vídeos e séries o dia todo. Conta com certificação IP67 que o torna resistente à água e poeira. Feito para durar, oferece até 6 atualizações de Android e 6 anos de atualizações de Segurança. Ele tem uma tela grande e com boa qualidade de imagem, um processador potente e câmeras que fazem fotos e vídeos de qualidade. Uma ótima opção para quem busca um smartphone intermediário com ótimo custo-benefício.",
    "Preco": "1.399",
    "Imagem": "/produtos/2.webp",
    "Tela": "6.7",
    "Camera": "50MP + 8MP + 5MP",
    "Processador": "Qualcomm Snapdragon 6 Gen 3 Octa-core",
    "Bateria": "5000mAh",
    "SistemaOperacional": "Android",
    "Conectividade": "5G"
  },
  {
    "id": 2,
    "nomeProduto": "Poco X7 Pro 5G 512GB 12GB",
    "DescricaoCurta": "Aparelho Celular de Alto Desempenho, perfeito para quem busca velocidade, qualidade de imagem e autonomia. Com tecnologia 5G e memória robusta, ele redefine a experiência móvel, sendo ideal para jogos, multitarefas e produção de conteúdo em 4K. Experimente a fluidez máxima em um dispositivo projetado para acompanhar o seu ritmo.",
    "created_at": "2026-03-13 23:25:55.463772+00",
    "DescricaoLonga": "Lista de Destaques\n\n✅ Tela AMOLED de 6.67 polegadas com cores vibrantes e nitidez superior.\n\n✅ Desempenho Multitarefa Imbatível: Equipado com 12GB de Memória RAM.\n\n✅ Armazenamento Massivo: 512GB internos para fotos, vídeos e aplicativos.\n\n✅ Processador Ultra-Rápido de 8 núcleos para fluidez em todas as tarefas e jogos.\n\n✅ Conectividade 5G para navegação e downloads em velocidade máxima.\n\n✅ Câmera principal de 50 MP com captura de vídeos em resolução 4K.\n\n✅ Bateria de longa duração para uso contínuo durante todo o dia.\n\n✅ Aceita Dual SIM, permitindo o uso de duas linhas telefônicas simultaneamente.",
    "Preco": "2.669",
    "Imagem": "/produtos/3.webp",
    "Tela": " 6.67",
    "Camera": "50 MP",
    "Processador": " Octa-core (8 núcleos)",
    "Bateria": "5000mAh",
    "SistemaOperacional": "Android",
    "Conectividade": "Wi-Fi e Bluetooth"
  },
  {
    "id": 3,
    "nomeProduto": "Apple iPhone 17 Pro Max 256GB",
    "DescricaoCurta": "iPhone 17 Pro Max. O iPhone mais potente já produzido. Tela brilhante de 6,9 polegadas*, estrutura unibody em alumínio, chip A19 Pro, câmeras traseiras de 48 MP e a maior duração de bateria em um iPhone.",
    "created_at": "2026-03-13 23:30:01.576956+00",
    "DescricaoLonga": "Avisos legais *A tela tem bordas arredondadas que se ajustam ao design curvo do aparelho dentro da sua forma retangular. Quando medida como um retângulo, a tela tem 6,27 polegadas (iPhone 17, iPhone 17 Pro), 6,55 polegadas (iPhone Air) ou 6,86 polegadas (iPhone 17 Pro Max) na diagonal. A área real de visualização é menor. **Em comparação com a parte de trás em vidro da geração anterior do iPhone. ***Em comparação com o iPhone da geração anterior. ****Todas as informações sobre a bateria dependem da configuração da rede e de vários outros fatores. Os resultados reais podem variar. A bateria tem um número limitado de ciclos de recarga e, se necessário, deverá ser substituída. A vida útil e a duração da bateria variam de acordo com o uso e a configuração. Consulte apple.com/br/batteries e apple.com/br/iphone/battery.html para obter mais informações.",
    "Preco": "10.124",
    "Imagem": "/produtos/4.webp",
    "Tela": "6.27",
    "Camera": "48MP",
    "Processador": "A19 Pro",
    "Bateria": "5000mAh",
    "SistemaOperacional": "IOS",
    "Conectividade": "Wi-Fi 7, Bluetooth 6, NFC"
  },
  {
    "id": 4,
    "nomeProduto": "Smartphone Samsung Galaxy S25 FE 128GB",
    "DescricaoCurta": "O Samsung Galaxy S25 FE 5G JetBlack é o smartphone que chega com recursos de câmeras, performance, inteligência artificial e design em uma combinação perfeita.",
    "created_at": "2026-03-13 23:35:01.416697+00",
    "DescricaoLonga": "om sua câmera câmera traseira tripla de 50MP (Wide) + 12MP (Ultra Wide) + 8MP (Tele) e frontal de 12MP com HDR, ele permite que você tenha novas maneiras de criar, retratos surpreendentes, selfies aprimoradas e edições de vídeo com IA (ProVisual Engine). O processador Samsung Exynos 2400 otimiza hardware e software para aprimorar a usabilidade da IA e toda a performance. Para você curte jogos o, Galaxy S25 FE permite que você aprimore sua jogabilidade com visuais envolventes e tenha um desempenho mais potente e estável. A tela Super AMOLED imersiva de 6,7\" é grande, brilhante com até 1900 nits e garante uma visualização imersiva nos seus vídeos e fotos. E a taxa de atualização de até 120Hz traz mais fluidez para seu conteúdo. Conta com novas funcionalidades da inteligência artificial, com o Google Gemini integrado em seu sistema operacional. Ele enriquece seu dia a dia com um assistente de IA que é fácil de usar, que entende o que você diz de maneira natural. Ele é equipado com 128GB de armazenamento interno e 8GB de memória RAM. Ainda conta com acabamento reforçado em Corning Gorilla Glass Victus+, resistência a água e a poeira (IP68) levando melhor proteção para o seu dia a dia. Atenção: Produto não acompanha fone de ouvido.",
    "Preco": "2.599",
    "Imagem": "/produtos/5.webp",
    "Tela": "6.7",
    "Camera": "50 MP",
    "Processador": "Samsung Exynos 2400",
    "Bateria": "4900mAh",
    "SistemaOperacional": "Android",
    "Conectividade": "5G"
  },
  {
    "id": 5,
    "nomeProduto": "Smartphone Motorola G86 256GB",
    "DescricaoCurta": "Explore o Motorola G86 na cor vermelha, um smartphone que redefine performance e imersão.",
    "created_at": "2026-03-13 23:44:52.159103+00",
    "DescricaoLonga": "Com impressionantes 256GB de armazenamento interno e 16GB de RAM (8GB físicos + 8GB RAM Boost), você terá espaço e velocidade de sobra para tudo. Sua tela pOLED HDR10+ com Gorilla Glass 7i de 6,7\", oferece cores vibrantes e resistência para o dia a dia. Capture momentos inesquecíveis com a câmera traseira dupla Principal Sensor Sony LYTIA 600 de 50MP e Ultra-wide & Macro de 8MP, além de selfies perfeitas com a frontal de 32MP. Experimente a velocidade do 5G em um aparelho completo e elegante. Conta com ultrarresistência militar MIL-STD 810H e certificações IP68 e IP69 com proteção contra água, poeira, areia e jatos em alta pressão. A bateria de 5200mAh oferece até 40 horas de uso.",
    "Preco": "1.469",
    "Imagem": "/produtos/6.webp",
    "Tela": null,
    "Camera": null,
    "Processador": null,
    "Bateria": null,
    "SistemaOperacional": null,
    "Conectividade": null
  },
  {
    "id": 6,
    "nomeProduto": "Fone De Ouvido Sem Fio Baseus Bowie E20 Bluetooth 5.3",
    "DescricaoCurta": "A Baseus se origina do nosso valor fundamental, Based on User, \"Baseado no Usuário\".    Somos apaixonados por criar produtos com design minimalistas, fácil de usar e uma textura que atende a todos os nossos clientes.",
    "created_at": "2026-03-14 21:05:08.914938+00",
    "DescricaoLonga": "Fone de Ouvido Sem Fio Baseus Bowie E20 Bluetooth 5.3 Preto\n\nCancelamento de Ruído Ambiental (ENC)\n\nConectividade Bluetooth 5.3\n\nGraves potentes com diafragma duplo de 12 mm\n\nDesign à prova d'água IPX5\n\nAté 33 horas de tempo de audição\n\nControles de toque inteligentes\n\nDiferenciais:\n\nEmitimos Nota Fiscal\n\nGarantia de 12 meses\n\nOriginal, Novo e Lacrado\n\nHomologado pela Anatel\n\nEnvio Imediato para todo o Brasil\n\nConteúdo da embalagem:\n\n1 Fone de Ouvido Sem Fio Baseus Bowie E20 Bluetooth 5.3 Preto\n\nSobre a Baseus",
    "Preco": "139.82",
    "Imagem": "/produtos/banner.webp",
    "Tela": null,
    "Camera": null,
    "Processador": null,
    "Bateria": "Até 33 horas",
    "SistemaOperacional": null,
    "Conectividade": "Bluetooth 5.3"
  },
  {
    "id": 7,
    "nomeProduto": "Smartphone OPPO A60 256GB Branco",
    "DescricaoCurta": "O OPPO A60 Branco é o smartphone ideal para quem busca qualidade e resistência em um único dispositivo. Com certificação de resistência militar a impactos",
    "created_at": "2026-04-03 21:27:17.547138+00",
    "DescricaoLonga": " O recurso Splash Touch permite que a tela continue funcionando com as mãos molhadas ou gotas d'água, garantindo facilidade e praticidade. Com uma poderosa bateria de 5100mAh e carregamento rápido Supervooc de 45W, mantém você conectado por muito mais tempo. A tela LCD de 6,67\" com brilho de até 1000 nits oferece uma experiência visual vibrante e detalhada, seja para assistir seus filmes ou séries favoritas. Equipado com o processador Qualcomm Snapdragon 6s 4G Gen1 de 2.1GHz, ele oferece desempenho rápido e eficiente, perfeito para multitarefa e entretenimento. Ele conta com 256GB de armazenamento interno e 8GB de memória RAM. A câmera traseira de 50MP garante fotos de alta resolução, enquanto a câmera frontal de 5MP proporciona selfies nítidas e de qualidade. Além disso, o recurso AI Portrait Retouching aprimora suas fotos com ajustes inteligentes, deixando suas imagens ainda mais incríveis.",
    "Preco": "1.376",
    "Imagem": "/produtos/7.webp",
    "Tela": "6,67",
    "Camera": "50MP",
    "Processador": "Qualcomm Snapdragon 6s 4G Gen1 de 2.1GHz",
    "Bateria": null,
    "SistemaOperacional": "Android",
    "Conectividade": null
  }
]